# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhmPnTCWztpANYL7rbM6xmRQp-EjC5-K
"""

a = 'ab'
print(a)